### ISSUE TITLE
Pip install in ve not working

### ISSUE THREAD

**Issue by africandave** [douglasrizzo/dodo_detector#10]
![Screenshot from 2022-08-26 23-22-18](https://user-images.githubusercontent.com/105605436/186992707-c2d256ec-3cb9-476a-9953-678e17aff041.png)
 What am I missing here?
I created a python 2.7 ve and installed tensorflow in it. Then I tried pip installing dodo_detector, but I get this error message.

**Comment by douglasrizzo** [comment]
Check if https://github.com/douglasrizzo/dodo_detector/issues/12#issuecomment-1239725714 solves your problem.
