### ISSUE TITLE
pip install dodo_detector[tf-cpu] not found

### ISSUE THREAD

**Issue by christenbc** [douglasrizzo/dodo_detector#2]
After doing this successfully:
`pip3 install git+https://github.com/douglasrizzo/dodo_detector.git`
I get an error with this command line:
`pip3 install dodo_detector[tf-cpu]`

> Could not find a version that satisfies the requirement dodo_detector[tf-cpu] (from versions: )
> No matching distribution found for dodo_detector[tf-cpu]

What is the reason behind?

**Comment by douglasrizzo** [comment]
As per the README, the instructions to install the package with either the `tf-cpu` or `tf-gpu` targets are to clone the repo and then install the locally cloned repo with the target:

    git clone https://github.com/douglasrizzo/dodo_detector.git
    pip install dodo_detector[tf-cpu] # for CPU support

AFAIK you can't use installation targets when installing directly from a git repo, something like this does not exist:

    pip3 install git+https://github.com/douglasrizzo/dodo_detector.git[tf-cpu]

Lastly, if you already installed dodo_detector, just `pip3 install tensorflow` and you should be set up.

**Comment by christenbc** [comment]
actually I did the reverse way, I installed tensorflow with object detection api and now I am installing your package.. so the only thing I should do is just:
`git clone https://github.com/douglasrizzo/dodo_detector.git` wherever, like {HOME}?
and then the git clone of your ros version in catkin_ws. Is that all, right?
I mean: `pip install dodo_detector[tf-cpu]` is not useful in that case, right?

**Comment by douglasrizzo** [comment]
Exactly.

**Comment by christenbc** [comment]
Perfect. So at this point, after installing and compiling also your ros package I set up the other dependencies:

- [frozen_inference_graph.pb](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md): then I go to COCO-trained models and download ssd_mobilenet_v2_coco as .tar.gz and extract everything in ~/catkin_ws/src/dodo_detector_ros
Afterwards I came https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt to get the mscoco_label_map.pbtxt.

Then I set up the main_config.yaml:
```
# ['sift', 'rootsift', 'ssd']
detector_type: ssd
# path to TensorFlow Object Detection API frozen inference graph
inference_graph: ~/.dodo_detector_ros/frozen_inference_graph.pb
# path to TensorFlow Object Detection API label map
label_map: ~/.dodo_detector_ros/mscoco_label_map.pbtxt

# confidence level to report objects as detected
ssd_confidence: 0.5

# minimum number of points to consider an object as present in the scene
sift_min_pts: 10

# path to the database used by the keypoint object detector
sift_database_path: ~/.dodo_detector_ros/sift_database

# the frame or tf that all object tfs will be published in relation to, leave blank to publish wrt. camera_link
# global_frame: map
```
Since I am not using SIFT I don't have any ~/.dodo_detector_ros/sift_database.

Then regarding the launcher:
```
<?xml version="1.0"?>
<launch>
    <remap from="/camera/rgb/image_color" to="/camera_floor/driver/color/image_raw"/>
    <remap from="/camera/depth/points" to="/camera_floor/driver/depth/color/points"/>

    
    <node name="dodo_detector_ros" pkg="dodo_detector_ros" type="detector.py" output="screen">
        <rosparam command="load" file="$(find dodo_detector_ros)/config/main_config.yaml"/>
    </node>
</launch>
```
Also did the chmod +x to your .py in the src folder.
Then I get this error after launching your detect_kinect.launch
<img width="1015" alt="Sketch" src="https://user-images.githubusercontent.com/45597426/55180914-399acf00-5193-11e9-9edb-3f6310d9a0a7.png">

**Comment by douglasrizzo** [comment]
It seems Python is not finding the package. If you've installed it with `pip3`, you have to check if ROS is indeed using Python 3 when calling `.py` scripts. I am almost sure ROS uses Python 2.7, so you'd have to install the dodo_detector package with `pip` or `pip2` or `python -m pip`.

**Comment by christenbc** [comment]
> It seems Python is not finding the package. If you've installed it with `pip3`, you have to check if ROS is indeed using Python 3 when calling `.py` scripts. I am almost sure ROS uses Python 2.7, so you'd have to install the dodo_detector package with `pip` or `pip2` or `python -m pip`.

how about tensorflow with the object detection api? should they also be in the 2.7 python version? in that case, that is not possible since tensorflow is not really compatible with such version but with python3

**Comment by douglasrizzo** [comment]
Doesn't ROS take into consideration the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) when choosing which interpreter to run the code? In the case of the `detector.py` node from _dodo_detector_ros_, the shebang is listed [here](https://github.com/douglasrizzo/dodo_detector_ros/blob/082a93ff394db1a8d20e375a71554de0e2d7955c/src/detector.py#L1).
You can try and change what's your default Python environment or change the shebang directly in your copy of the package to use `python3` and test it.

**Comment by christenbc** [comment]
All right, when I put `#!/usr/bin/env python3` instead then I get a different error.
![IMG_20190401_165332](https://user-images.githubusercontent.com/45597426/55333768-9a325080-54a0-11e9-9ad3-807edf3f0720.jpg)
It is not a solution to install your dodo_detector by using pip2, that is installing it in python2 because tensorflow is in python3. How did you manage to run tensorflow, and your package in the same python environment?

**Comment by douglasrizzo** [comment]
Sorry, it's been some time since I last worked with ROS.
You said previously that TensorFlow is not supported under Python 2.7. I did a search using `pip search` for Python 2.7 and I found `tensorflow` listed in the packages. I also checked the [installation instructions of the models repository](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) and they do not mention a specific version of Python.
Lastly, I used [py_compile](https://docs.python.org/2/library/py_compile.html) to check the compatibility of my Python code with Python 2.7 and everything checks out.

At this point, I believe everything I did with Python + TensorFlow + ROS had to be done with Python 2.7 and not Python 3...

Can you try to install TensorFlow under Python 2.7, point the shebang of `detector.py` to Python 2.7 again and give it a try? Also make sure Python 2.7 finds the models repo.
