### ISSUE TITLE
opencv-python not found

### ISSUE THREAD

**Issue by sohartma** [douglasrizzo/dodo_detector#4]
Hello,

I'm trying to install the package on my RasPi with:
python3 -m pip install git+https://github.com/douglasrizzo/dodo_detector.git

and i get this error:
Could not find a version that satisfies the requirement opencv-python (from dodo-detector===0.6.1) (from versions: )
No matching distribution found for opencv-python (from dodo-detector===0.6.1)

Is it because i have to install opencv first from https://pypi.org/project/opencv-python/ ?
I've already tried this for hours now, but it doesn't work.

**Comment by douglasrizzo** [comment]
Hi there. `pip` should have found and installed the package `opencv-python` for you. You can try installing it separately with `pip install opencv-python` and see what happens.

I just ran `pip search opencv-python` on my machine and found the package. It is indeed available through `pip`.
