### ISSUE TITLE
Cannot launch detector.py 

### ISSUE THREAD

**Issue by sohartma** [douglasrizzo/dodo_detector#5]
Hi,

I'm trying to launch the package with roslaunch dodo_detector_ros detect_camera.launch 
The camera node starts fine and detects my camera, but i receive this error:
ERROR: cannot launch node of type [dodo_detector_ros/detector.py]: can't locate node [detector.py] in package [dodo_detector_ros]
When starting the node individually, the output is: 

/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Traceback (most recent call last):
  File "detector.py", line 12, in <module>
    from dodo_detector.detection import SingleShotDetector, KeypointObjectDetector
ImportError: No module named dodo_detector.detection

How do i fix this?

**Comment by sohartma** [comment]
Yes, the problem is definitely not with dodo_detector! 

1. I'm using Ubuntu 16.04.6 LTS (GNU/Linux 4.19.50-v7+ armv7l)
2. Yes
3. I've installed miniconda thanks to your advice, however I don't really know how to use it. Also i couldn't start rosserial and a ros package I've worked with recently after installing miniconda.

Right now, I'm trying to follow the instruction from: https://github.com/phopley/rodney-project/blob/master/Articles/tensorflow/pi_image.md to install tensorflow. That person has the same setup (even uses an ubiquity image for the Pi like me).
I downloaded tf 1.14. cp27 arm7vl.
And when installing tensorflow, I'm getting the same error:
``
Collecting numpy<2.0,>=1.14.5 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/0c/e8/c49cb52ed2ad734efb49eb1f7766888b0e65df1848f71fa7f7fd52183392/numpy-1.18.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KCg3Ag/numpy/setup.py", line 32, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KCg3Ag/numpy/
``

After hours of reasearch i tried upgrading the setuptools, reinstalling pip to the system version (81.1.). I've tried upgrading numpy with pip to version 1.15. I've tried deinstalling numpy with pip and apt and installing it again with apt. Nothing worked so far.

**Comment by sohartma** [comment]
@douglasrizzo Update: I've installed tensorflow without dependencies. I'm now installing matplotlib, also for python2. And it's the same issue. pip install tries to install the newest version of matplotlib, which doesn't work with python2. It was the same with the tensorflow installation. pip install tried installing the newest version of numpy, which isn't compatible with python2.

**Comment by douglasrizzo** [comment]
It looks like you're using a custom Linux image. You should make sure that their Python installation is in working condition to install updated packages, or else you'll be stuck with what is installed.

In the tutorial you linked, they already teach you how to install TensorFlow and the object detection API (step 3) for Python 2.7. Just make sure when you call `pip`, you're referring to `pip` for Python 2.7 and not Python 3. However, their TensorFlow is downloaded from a different repository, not the official ones.

You can try to clone this repository, ignore its requirements and install them separately as needed. You don't really need `opencv-python`, but you'll definitely need `numpy`. You'll also need to test `dodo_detector` against TensorFlow 1.11, as I've only tested it against TensorFlow>=1.13 and <=1.15.

Lastly, if you are having overall problems with Python (not just related to `dodo_detector`), you can still try to install and use Anaconda in your Ubuntu image.

Ubuntu 16.04 comes with Python 2.7 and 3.5 installed. These are system installations and their packages are usually installed through apt (e.g. `apt install python2-numpy`) and not through `pip`.

Anaconda perform a standalone installation of Python, which is independent from your OS and can be updated as you please. Just create a Python 2.7 enviroment, activate it and use python and pip as you normally do:

    conda create -n py2 python=2.7 anaconda
    conda ativate py27

Maybe this will solve your problem.
